name: atre_website
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.7.0
  hovering: ^1.0.4
  google_fonts: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_widget_from_html: ^0.10.3
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # - images/a_dot_ham.jpeg

  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
          style: italic
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
